project:
  type: website
  output-dir: docs

website:
  title: "Gavin le Fey"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: 
      light: sandstone
      dark: slate
    css: styles.css
    toc: true

editor: visual

